name: Release to Charmhub

on:
  workflow_dispatch:
    inputs:
      channel:
        description: "The channel where the charm is going to be released to"
        required: true
        default: "stable"
        type: choice
        options:
          - stable
          - candidate
          - beta
          - edge

jobs:
  release-to-charmhub:
    name: Release to CharmHub
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Charmcraft
        run: |
          sudo snap install charmcraft --channel 3.x/stable --classic

      - name: Build bundle
        run: |
          charmcraft pack

      - name: Create bundle revision and release to Charmhub
        run: |
          charmcraft upload --name=vantage-agents --release=${{ github.event.inputs.channel }} vantage-agents.zip
        env:
          CHARMCRAFT_AUTH: ${{ secrets.CHARMCRAFT_AUTH }}
